spring:
  profiles:
    active: dev

---
# 开发环境
server:
  port: 8079
spring:
  config:
    activate:
      on-profile: dev
---
# 生产环境

server:
  port: 8081
spring:
  config:
    activate:
      on-profile: pro
---
# 测试环境
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: test