spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_db
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

